### PR TITLE
Update packaging to use more modern python practices

### PR DESCRIPTION
**Pull request by jasongrout**
This updates the cookiecutter to use setup.cfg, etc. See https://setuptools.readthedocs.io/en/latest/build_meta.html

To generate a wheel, I think recommended practice to now use `python -m build`, for example.

- [x] Add install.json for the jlab extension
- [x] Error: `warning package.json: No license field`

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @ibdafna

**Comment by jasongrout** [comment]
`python -m build` doesn't currently work because yarn cannot find `jupyter labextension build` - perhaps somehow a consequence of the virtual env the build process sets up?

Also, it's unfortunate that the pyproject.toml cannot say that nodejs or yarn are required :(.

**Comment by jasongrout** [comment]
> `python -m build` doesn't currently work because yarn cannot find `jupyter labextension build` - perhaps somehow a consequence of the virtual env the build process sets up? `python -m build --no-isolation` does work if the build dependencies are installed.

This is because of this bug in `build`: https://github.com/pypa/build/issues/214

So this PR is stalled until at least that bug is fixed and released.

**Comment by vidartf** [comment]
That bug was fixed and released yesterday 🚀

**Review by vidartf — APPROVED** [review]

**Pull request merged**
