### PR TITLE
Ensure __webpack_public_path__ for nbextension

### PR DESCRIPTION
**Pull request by vidartf**
C.f. #37

### CODE REVIEW

**Comment by vidartf** [comment]
@jasongrout Does this look OK?

**Comment by maartenbreddels** [comment]
I thought we wanted to get rid of it, can you explain why we would want to add it?

**Comment by vidartf** [comment]
You want to get rid of it for jupyterlab extensions, but you might need it for classic notebook extensions.

**Comment by vidartf** [comment]
The docstring describes it more fully. However, the concern mentioned there doesn't matter for lab, where everything is bundled (including static assets).

**Comment by maartenbreddels** [comment]
In my recollection (might be a gitter chat) there was no use for this (any more?)

**Comment by jasongrout** [comment]
There could be a use for it in the classic notebook. I don't know anyone *actually* using it.

**Comment by SylvainCorlay** [comment]
We may want to check this on ipyleaflet wrt  marker images. I think that we don't need it anymore though.

**Comment by vidartf** [comment]
The Line om ipyleaflet is here: https://github.com/jupyter-widgets/ipyleaflet/blob/658b21564dffaa85941bf73d1875121786a6ff92/js/src/notebook.js

**Comment by SylvainCorlay** [comment]
It seems to be matching perfectly!

**Comment by maartenbreddels** [comment]
I know what the reason was I removed it in ipyvolume (and now also in ipywebrtc)
I include the index.js for the Jupyter Lab extension, and that causes all widgets to fail without any error msg. This caused me quite some time to figure out **again**, so I though I should write it down at least somewhere. Sigh.. but, ipywebrtc in Jupyter Lab is working!

**Pull request merged**
