### PR TITLE
Add suggestion to bump view and model version in widget implementations

### LINKED ISSUE #84: Release instructions do not suggest to bump the model/view version numbers
The problems I was experiencing in #82 were a result of the fact that I had not bumped the model/view versions in the widget definition [as suggested](https://github.com/idom-team/idom-jupyter/pull/9#issuecomment-762678935) by @jasongrout. This is probably because the `RELEASE.md`file does not suggest doing so.

### PR DESCRIPTION
**Pull request by rmorshea**
Fixes #84

- Improve formatting of RELEASE.md
- Add suggestion to bump view and model version in widget implementations

### CODE REVIEW

**Comment by jasongrout** [comment]
All I see here is adding idom-jupyter to the example list. Happy to merge this, but...was there more to this PR, given the description?

**Comment by rmorshea** [comment]
Odd, something got screwed up. Will fix that soon.

**Comment by rmorshea** [comment]
I actually had a separate PR for adding `idom-jupyter` to the list of example usages: https://github.com/jupyter-widgets/widget-cookiecutter/pull/77/files

**Comment by rmorshea** [comment]
@jasongrout the PR has been corrected.

**Pull request closed without merging**
