### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by jtpio** [comment]
Looks like it's not triggered because the PR is from a fork?

**Comment by martinRenou** [comment]
I suppose yes

**Comment by jtpio** [comment]
A workaround to trigger CI would be to open a test PR on the fork: https://github.com/martinRenou/widget-cookiecutter

And check that GH actions are enabled there.

**Comment by martinRenou** [comment]
Nice! That is very useful :)

**Comment by martinRenou** [comment]
It works, let's merge and test the other PR

**Pull request merged**
